### PR TITLE
Sanitize query params and body

### PR DESCRIPTION
**Pull request by eBaeza**
Actually when try to sanitize query params from Route Validator doesn't work

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @eBaeza! 👋 

As you see your code is breaking the current build.
Please, make it works if you want us to merge your modification.

**Comment by eBaeza** [comment]
@RomainLanz ok, let me check why is happen this.

**Review by RomainLanz — APPROVED** [review]

**Review by thetutlage — APPROVED** [review]
Looks neat to me

**Comment by thetutlage** [comment]
Thanks 😄

**Pull request merged**
