### PR TITLE
added equalTo rule

### PR DESCRIPTION
**Pull request by popovicieduard**
## Proposed changes

added equalTo rule as discussed here: https://github.com/adonisjs/core/discussions/1475#discussioncomment-52260

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/validator/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by thetutlage** [comment]
I believe we should add support for `refs`, otherwise the rule is pretty much useless. The refs are required for using dynamic values inside the schema

**Comment by popovicieduard** [comment]
added the functionality, forgot to add the adonis-typings, commiting right now.

**Comment by thetutlage** [comment]
Nice. Can you please also add one test using refs? Also, it will be nice, if you can open a parallel PR for the docs too.

**Comment by popovicieduard** [comment]
Sure

**Comment by popovicieduard** [comment]
PR for docs created: https://github.com/adonisjs/adonisjs.com/pull/97

**Comment by thetutlage** [comment]
Thanks 😄

**Pull request merged**
