### PR TITLE
implement better custom msgs

### PR DESCRIPTION
**Pull request by ctf0**
https://github.com/adonisjs/adonis-validation-provider/issues/8 this is what i meant. 

for the validation files, heres a repo to be used as a central for other locales as well.
https://github.com/ctf0/adonis-validation-messages

### CODE REVIEW

**Comment by RomainLanz** [comment]
Why do you want to do that?

This is how I achieve something similar: https://gist.github.com/RomainLanz/445760d1d4f19b10881175e6cf3b74c5

**Comment by ctf0** [comment]
aside from that this PR will be mostly rejected, the reason after it is 

1- to have a standardized file with all the validation msgs that the user can change & be able to easily share with others if it was better than the current

2- it works with multilang, where ur solution = the default are hardcoded and wont support different locales

on a side note, i made a macro for the auto validation and redirection which u can find it @ https://ctf0.wordpress.com/2016/11/26/adonisjs/

however i tried to make something like
```js
yield this.validation(request, rules)
```
were thats all the user need to call in the controller to take care of all the validation steps "something like laravel", but i kept getting an error about headers cant be set, if u r interested we can talk on gitter.

**Comment by thetutlage** [comment]
Okay what should I do when I want to have different messages for same validation?

For example: In signup I want to say `Enter your email address to signup`. Whereas during login it will be `Enter your email to login`?

**Comment by ctf0** [comment]
in that case u add ur custom validation as normal as a 3rd arg

```js
messages = messages || ValidationMessages()
```

**Comment by thetutlage** [comment]
In that case this file is of no use. Closing the PR since these kind of decisions must be taken at the application level

**Comment by ctf0** [comment]
@thetutlage  on the contrary, adding any extra logic to the file will take advantage of the multi-lang support while using the 3rd arg directly would not, so its really up to the user to decide which to use.

**Pull request closed without merging**
